# Generated by Django 3.0.3 on 2020-07-05 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('spot', models.CharField(max_length=250)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Celebrite',
                'verbose_name_plural': 'Celebrites',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComingSoon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'ComingSoon',
                'verbose_name_plural': 'ComingSoons',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crews',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('plot', models.TextField()),
                ('banner', models.ImageField(upload_to='')),
                ('year', models.DateField()),
                ('rating', models.IntegerField(choices=[(0, 'NR - Not rated'), (1, 'G - General Audiences'), (2, 'PG - Parental Guidance Suggested'), (3, 'R - Restricted')], default=0)),
                ('category', models.CharField(choices=[('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Sport', 'Sport'), ('WAR', 'WAR'), ('Western', 'Western'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Romance', 'Romance'), ('Action', 'Action'), ('Musicals', 'Musicals')], max_length=255)),
                ('post', models.BooleanField(default=True)),
                ('runtime', models.PositiveIntegerField()),
                ('website', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='')),
                ('detail', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'OurUser',
                'verbose_name_plural': 'OurUsers',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('born', models.DateField()),
                ('died', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': '',
                'ordering': ('first_name', 'last_name'),
                'managed': True,
            },
            managers=[
                ('persons', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TvMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showtime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'TvMovie',
                'verbose_name_plural': 'TvMovies',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TvName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'TvName',
                'verbose_name_plural': 'TvNames',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, '👍'), (2, '👍👍'), (3, '👍👍👍'), (4, '👍👍👍👍'), (5, '👍👍👍👍👍')])),
                ('review', models.TextField()),
                ('voted_on', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
