# Generated by Django 3.0.3 on 2020-07-05 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tvmovie',
            name='movie',
            field=models.ManyToManyField(to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='tvmovie',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tv_names', to='movie.TvName'),
        ),
        migrations.AddField(
            model_name='role',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='role',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Person'),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='f_movie',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='ouruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='acting_credits', through='movie.Role', to='movie.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='castcrew',
            field=models.ManyToManyField(blank=True, related_name='crew_credits', through='movie.Crew', to='movie.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed', to='movie.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.ManyToManyField(blank=True, related_name='writers', to='movie.Person'),
        ),
        migrations.AddField(
            model_name='crew',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='crew',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='crew_movie', to='movie.Person'),
        ),
        migrations.AddField(
            model_name='comingsoon',
            name='movie',
            field=models.ManyToManyField(related_name='coming_movies', to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='celebrite',
            name='movie',
            field=models.ManyToManyField(related_name='celebrity_movies', to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='celebrite',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='celebrite_name', to='movie.Person'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'movie')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('movie', 'person', 'name')},
        ),
    ]
